### ISSUE TITLE
博主，这个爬虫是从网页还是app爬取的

### ISSUE THREAD

**Issue by wangshiyu777** [death00/wechat-mp-data-crawl#1]
博主，这个爬虫是从网页还是app爬取的，微信公众号文章？

**Comment by death00** [comment]
@wangshiyu777 只是爬取微信公众平台内的数据，比如用户画像、收入这种

**Comment by wangshiyu777** [comment]
最近也在学习相关抓取，方便的话加个微信，交流一下（vx: 731444260 ）
